package hbi.core.item.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.excel.annotation.ExcelJoinColumn;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import hbi.core.shop.dto.Shop;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "test_shop_item")
public class ShopItem extends BaseDTO {

     public static final String FIELD_ITEM_ID = "itemId";
     public static final String FIELD_SHOP_ID = "shopId";
     public static final String FIELD_ITEM_NAME = "itemName";
     public static final String FIELD_ITEM_PRICE = "itemPrice";
     public static final String FIELD_ITEM_STOCK = "itemStock";


     @Id
     @GeneratedValue
     private Long itemId;

    @ExcelJoinColumn(JoinTable = Shop.class,JoinColumn = Shop.FIELD_SHOP_ID,AlternateColumn = Shop.FIELD_SHOP_NAME)
     private Long shopId; //商店ID

     @Length(max = 255)
     private String itemName; //商品名称

     private Long itemPrice; //商品单价

     private Long itemStock; //商品库存

    public ShopItem() {
    }

    public ShopItem(Long shopId) {
        this.shopId = shopId;
    }

    public void setItemId(Long itemId){
         this.itemId = itemId;
     }

     public Long getItemId(){
         return itemId;
     }

     public void setShopId(Long shopId){
         this.shopId = shopId;
     }

     public Long getShopId(){
         return shopId;
     }

     public void setItemName(String itemName){
         this.itemName = itemName;
     }

     public String getItemName(){
         return itemName;
     }

     public void setItemPrice(Long itemPrice){
         this.itemPrice = itemPrice;
     }

     public Long getItemPrice(){
         return itemPrice;
     }

     public void setItemStock(Long itemStock){
         this.itemStock = itemStock;
     }

     public Long getItemStock(){
         return itemStock;
     }

     }
