package hbi.core.shop.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.core.annotation.Children;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import hbi.core.item.dto.ShopItem;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import java.util.List;

@ExtensionAttribute(disable=true)
@Table(name = "test_shop")
public class Shop extends BaseDTO {

     public static final String FIELD_SHOP_ID = "shopId";
     public static final String FIELD_SHOP_NAME = "shopName";
     public static final String FIELD_SHOP_ADDRESS = "shopAddress";
     public static final String FIELD_TOTAL_AMOUNT = "totalAmount";
     public static final String FIELD_CREATE_TIME = "createTime";


     @Id
     @GeneratedValue
     private Long shopId;

     @Length(max = 255)
     private String shopName; //店铺名称

     @Length(max = 255)
     private String shopAddress; //店铺地址

     private Long totalAmount; //销售金额

     private Date createTime; //创建时间

    @Children
    @Transient
    private List<ShopItem> itemList;

    public Shop() {
    }

    public Shop(Long shopId) {
        this.shopId = shopId;
    }



    public Shop(String shopName, String shopAddress, Long totalAmount, Date createTime) {
        this.shopName = shopName;
        this.shopAddress = shopAddress;
        this.totalAmount = totalAmount;
        this.createTime = createTime;
    }

    public List<ShopItem> getItemList() {
        return itemList;
    }

    public void setItemList(List<ShopItem> itemList) {
        this.itemList = itemList;
    }

    public void setShopId(Long shopId){
         this.shopId = shopId;
     }

     public Long getShopId(){
         return shopId;
     }

     public void setShopName(String shopName){
         this.shopName = shopName;
     }

     public String getShopName(){
         return shopName;
     }

     public void setShopAddress(String shopAddress){
         this.shopAddress = shopAddress;
     }

     public String getShopAddress(){
         return shopAddress;
     }

     public void setTotalAmount(Long totalAmount){
         this.totalAmount = totalAmount;
     }

     public Long getTotalAmount(){
         return totalAmount;
     }

     public void setCreateTime(Date createTime){
         this.createTime = createTime;
     }

     public Date getCreateTime(){
         return createTime;
     }

     }
