package hbi.core.region.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "region")
public class Region extends BaseDTO {

     public static final String FIELD_REGION_ID = "regionId";
     public static final String FIELD_REGION_CODE = "regionCode";
     public static final String FIELD_REGION_NAME = "regionName";
     public static final String FIELD_PARENT_ID = "parentId";
     public static final String FIELD_REGION_LEVEL = "regionLevel";
     public static final String FIELD_REGION_ORDER = "regionOrder";
     public static final String FIELD_REGION_NAME_EN = "regionNameEn";
     public static final String FIELD_REGION_SHORTNAME_EN = "regionShortnameEn";


     @Id
     @GeneratedValue
     private Double regionId;

     @NotEmpty
     @Length(max = 100)
     private String regionCode;

     @NotEmpty
     @Length(max = 100)
     private String regionName;

     private Double parentId;

     private Double regionLevel;

     private Double regionOrder;

     @NotEmpty
     @Length(max = 100)
     private String regionNameEn;

     @NotEmpty
     @Length(max = 10)
     private String regionShortnameEn;


     public void setRegionId(Double regionId){
         this.regionId = regionId;
     }

     public Double getRegionId(){
         return regionId;
     }

     public void setRegionCode(String regionCode){
         this.regionCode = regionCode;
     }

     public String getRegionCode(){
         return regionCode;
     }

     public void setRegionName(String regionName){
         this.regionName = regionName;
     }

     public String getRegionName(){
         return regionName;
     }

     public void setParentId(Double parentId){
         this.parentId = parentId;
     }

     public Double getParentId(){
         return parentId;
     }

     public void setRegionLevel(Double regionLevel){
         this.regionLevel = regionLevel;
     }

     public Double getRegionLevel(){
         return regionLevel;
     }

     public void setRegionOrder(Double regionOrder){
         this.regionOrder = regionOrder;
     }

     public Double getRegionOrder(){
         return regionOrder;
     }

     public void setRegionNameEn(String regionNameEn){
         this.regionNameEn = regionNameEn;
     }

     public String getRegionNameEn(){
         return regionNameEn;
     }

     public void setRegionShortnameEn(String regionShortnameEn){
         this.regionShortnameEn = regionShortnameEn;
     }

     public String getRegionShortnameEn(){
         return regionShortnameEn;
     }

     }
